#!/usr/bin/env python3

from pathlib import Path
from shutil import copy2
from plistlib import load, dump
from subprocess import run

DOCK_PLIST = Path.home() / "Library/Preferences/com.apple.dock.plist"
PRIVILEGES_BUNDLE_ID = "corp.sap.privileges"


def backup_dock_plist():
    backup_path = DOCK_PLIST.with_name(f"{DOCK_PLIST.name}.bak")
    copy2(DOCK_PLIST, backup_path)


def restart_dock():
    run(["killall", "Dock"])


def main():
    with open(DOCK_PLIST, "rb") as fp:
        dock_prefs = load(fp)

    has_privileges_app = any(
        app.get("tile-data", {}).get("bundle-identifier") == PRIVILEGES_BUNDLE_ID
        for app in dock_prefs["persistent-apps"]
    )

    if not has_privileges_app:
        return

    backup_dock_plist()

    # Remove app from persistent apps where bundle identifier is equal to corp.sap.privileges.
    dock_prefs["persistent-apps"] = [
        app
        for app in dock_prefs["persistent-apps"]
        if app.get("tile-data", {}).get("bundle-identifier") != PRIVILEGES_BUNDLE_ID
    ]

    with open(DOCK_PLIST, "wb") as fp:
        dump(dock_prefs, fp)

    restart_dock()


if __name__ == "__main__":
    main()
